encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("createnew/", views.createNew, name="createnew"),
    path('<str:title>/edit/', views.edit, name="edit"),
    path('random_page/', views.random_page, name="random_page"),

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput

class SearchForm(forms.Form):
    search = forms.CharField(label='Search Encyclopedia', required=False)

class CreateNewEntryForm(forms.Form):
    title = forms.CharField(label="Title", )
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Type the content of the entry in markdown format.'}), label = "")

encyclopedia/views.py
from django.shortcuts import render
from . import util, forms
import random
import markdown2
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
form = forms.SearchForm()

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": form
    })

def entry(request, title):
    try:
        content = markdown2.markdown(util.get_entry(title))
    except:
        content = None
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": content,
        "form": form
    })

def search(request):
    if(request.method == 'GET'):
        form = forms.SearchForm(request.GET)
        if(form.is_valid()):
            search = form.cleaned_data['search'].lower()
            entries = util.list_entries()
            if(search in [x.lower() for x in entries]):
                return entry(request, search)
            else:
                queryResults = [x for x in entries if search.lower() in x.lower()]
                return render(request, "encyclopedia/search.html", {
                    "search": search,
                    "queryResults": queryResults,
                })

def createNew(request):
    if request.method == "GET":
        return render(request, "encyclopedia/createnew.html")

    # If route accessed via POST (i.e. after submitting form)
    elif request.method == "POST":

        # Stores entry's name and content
        form = request.POST
        title = form['title']
        content = form['content']

        # Checks file does not already exist and renders result (success / fail)
        entries = util.list_entries()

        print(title)
        print(entries)

        for item in entries:
            if title.lower() == item.lower():
                return render(request, "encyclopedia/result.html", {
                    "message": "Error! New entry was NOT added."
                })

        util.save_entry(title, content)
        return render(request, "encyclopedia/result.html", {
            "message": "Success! New entry added."
        })

def edit(request, title):
    if request.method == "GET":

        content = util.get_entry(title)

        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": content,
        })
    elif request.method == "POST":
        form = request.POST
        title = form['title']
        content = form['content']
        util.save_entry(title, content)
        return HttpResponseRedirect(reverse("wiki:entry", kwargs={'title': title}))

def random_page(request):
    entries = util.list_entries()
    page = random.choice(entries)
    #return HttpResponse(page)
    return HttpResponseRedirect(reverse("wiki:entry", kwargs={'title': page}))

encyclopedia/templates/encyclopedia/createnew.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h1> New Page </h1>

<!-- New entry page. Form with two fields: name and content (textarea) -->
<form action="{% url 'wiki:createnew' %}" method="post">
    <div class="form-group">
        <label for="title">Entry Title:</label>
        <input type="text" name="title" id="title" class="form-control">
    </div>
    <div class="form-group">
        <label for="content">Entry Content:</label>
        <textarea class="form-control" name="content" rows="15" id="content"></textarea>
    </div>
    {% csrf_token %}
    <button class="btn btn-primary">Submit</button>
</form>

{% endblock %}
Footer

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h1> Edit Page </h1>


<form method="post">
    <!-- Form for page's title, autofilled via value -->
    <div class="form-group">
        <label for="title">Entry Title:</label>
        <input type="text" name="title" id="title" class="form-control" value={{title}} readonly>
    </div>
    <!-- Form for page's content (textarea), autofilled between angle brackets -->
    <div class="form-group">
        <label for="content">Entry Content:</label>
        <textarea class="form-control" name="content" rows="15" id="content">{{content}}</textarea>
    </div>
    {% csrf_token %}
    <button class="btn btn-primary">Save</button>
</form>

{% endblock %}

<!-- {#<form action="{% url 'wiki:edit' %}" method="post"> #} -->

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body%}
    {% if content != None %}
        {{ content|safe }}
        <a href='{{title}}/edit/' class="btn btn-primary" role="button"> Edit Page</a>

    {% else %}
        <h1 style="text-align: center">
            Error (404): No such entry exists.
        </h1>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href = "{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    <div class="row">
      <div class="sidebar col-lg-2 col-md-3">
        <h2>Wiki</h2>
        <form action="{% url 'wiki:search' %}" method="GET" class="search">
          {{form}}
          <!-- <input id="search" type="submit" value="search" /> -->
        </form>
        <div>
          <a href="{% url 'wiki:index' %}">Home</a>
        </div>
        <div><a href="{% url 'wiki:createnew' %}">Create New Page</a></div>
        <div><a href="{% url 'wiki:random_page' %}">Random Page</a></div>
        {% block nav %} {% endblock %}
      </div>
      <div class="main col-lg-10 col-md-9">{% block body %} {% endblock %}</div>
    </div>
  </body>
</html>

encyclopedia/templates/encyclopedia/result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<!-- Entry saved or not? -->
<h3> {{ message }} </h3>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
<h1>Results for "{{ search }}"</h1>

<ul>
    {% for entry in queryResults %}
        <li><a href = "{% url 'wiki:entry' title=entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}